### ISSUE TITLE
In Fx 67 beta, there is a blank popup windows when download something.

### ISSUE THREAD

**Issue by ershiwo** [RossWang/Aria2-Integration#52] opened 2019-03-28 12:17 UTC
Environment: Firefox 67 beta 5 on Windows 10 1809
Version: 0.4.2

When start download something, the popup window appears a blank page with no web elements. 
![2019-03-28_201415](https://user-images.githubusercontent.com/14813866/55157072-7d430800-5196-11e9-8bee-3e6f3587d8b6.png)

**Comment by RossWang** [comment] 2019-03-29 09:20
Cannot reproduce the issue.
Do anyone else have this issue?

**Comment by RossWang** [comment] 2019-06-14 09:59
Do you still have this issue? If not, I will going to close this case.

**Comment by ershiwo** [comment] 2019-06-15 03:37
It has been resolved since a Firefox update, thanks.


来自 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Closed** 2019-06-15 03:38 UTC
Labels: question
